export type EndingKey = "a" | "b";

export type PhotoGroupKey = "return" | "makeup" | "solo" | "discover" | "waiting";
export type PhotoPriority = "hero" | "normal" | "fragment";

export type PhotoMemory = {
  id: string;
  src: string;
  alt: string;
  group: PhotoGroupKey;
  priority: PhotoPriority;
  date: string;
  location?: string;
  caption: string;
  tag?: "FOR YOU" | "KEEP";
};

export const letterContent = {
  meta: {
    title: "写给另一颗星",
    subtitle: "我们曾短暂地经过彼此的世界。",
  },
  intro: {
    chapter: "一封信",
    time: "今夜",
    title: "写给另一颗星",
    subtitle: "我们曾短暂地经过彼此的世界。",
    paragraphs: [
      "共有4段，写在不同时间，全程友情没有变质，请放心观看！",
      "原稿的段一写于分别后的第一周里（已丢入碎纸机，嘿嘿）",
      "想说的太多，就会变成好多好多字，但这并不一定好，表达出最想说的就好，也因此有了这一版的段一",
    ],
    action: "开始读这封信",
  },
  apology: {
    chapter: "失礼",
    time: "分别后的第一周",
    distance: [
      "在那天之前，余音眼里的我会是什么样的人呢？",
      "仅从网上的相识，大抵我会是一个比较不错的样子？",
      "我也一直觉得，如果距离近了，见到彼此真实的样子，失望可能也会随之变多。",
      "所以过去的我会下意识避免和远方相识的人线下见面",
    ],
    meetingLead: "但这次巧合下的相逢却带来了很多不一样的色彩",
    memories: [
      {
        id: "guide",
        label: "不当导游啦",
        text: "会在一开始说着“不当导游啦”，却又偷偷担心，这会不会是唯一一次和你见面的机会",
        detail: "",
      },
      {
        id: "sleepless",
        label: "前一晚",
        text: "会在约定的前一晚失眠，第二天又早早的爬起来不想迟到",
        detail: "",
      },
      {
        id: "debuff",
        label: "晕车debuff",
        text: "会在触发晕车debuff后还想着继续挑战，然后成功阵亡.jpg",
        detail: "debuff",
      },
      {
        id: "panda",
        label: "小熊猫玩偶",
        text: "会想在离开前去商店买一只小熊猫玩偶给你，又担心走太远会耽误你去博物馆的行程",
        detail: "",
      },
      {
        id: "crocodile",
        label: "鳄鱼签",
        text: "最后只留下了一只暗中观察的鳄鱼签，后面想起来，还是觉得好遗憾（动物玩偶很可爱很适合你）",
        detail: "",
      },
    ],
    afterMeeting: [
      "好好回想那天的情绪，欣喜大概还是占绝大部分。",
      "也正如此，分别后才会比想象中多出些失落。",
      "后来也想过，是不是一个人待得太久，只是突然有人陪着走了一段路，就会让我如此不习惯。",
      "思来想去又不完全是。",
      "我也不觉得换成随便一个人，都会有类似的结果。",
      "哈哈哈不是在吹捧你！",
      "只是吧，可能对那时候我的世界来说，一切就是刚刚好而已",
    ],
    similarityIntro: "一部分特别来自那些意外的相似。",
    similarities: [
      {
        id: "food",
        label: "随缘吃饭",
        image: "/images/resonance/food.webp",
        alt: "两个火柴人处在不同房间，各自错过饭点，饭菜仍未打开",
      },
      {
        id: "home",
        label: "喜欢一个人宅着",
        image: "/images/resonance/home.webp",
        alt: "两个火柴人各自在安静的角落读书和听音乐",
      },
      {
        id: "travel",
        label: "一个人随缘远行",
        image: "/images/resonance/travel.webp",
        alt: "两个火柴人背着小包，独自在不同的星空小路上远行",
      },
      {
        id: "smoke",
        label: "讨厌二手烟",
        image: "/images/resonance/smoke.webp",
        alt: "两个火柴人在不同地点捂住鼻子，快速跑离画外飘来的香烟烟雾",
      },
      {
        id: "douyin",
        label: "讨厌抖音",
        image: "/images/resonance/offline.webp",
        alt: "两个火柴人处在不同房间，中央是嵌套禁止标识的抖音图标",
      },
      {
        id: "night",
        label: "喜欢独自一人的深夜...",
        image: "/images/resonance/night.webp",
        alt: "两个火柴人在各自的夜晚空间里独处，一个读书，一个望月",
      },
    ],
    afterSimilarity: "很多其实很小的事情，但知道时，会有种“原来你也是这样”的开心。",
    envyTurn: [
      "如果只是相似，大概不会让我后来想这么多。",
      "更多的还是羡慕。",
    ],
    envy: "我由衷地羡慕着选择了想学的专业的你，即使在理解到你现在的辛苦和难受之后。",
    possibility: "或许是从你身上，看到了某种自己曾经想成为、或者直到现在仍然想成为的可能。",
    closing: [
      "也是这些欣喜、相似、还有些许的羡慕，最后变成了这封长长的信。",
      "嘿嘿，写时会担心，会不会给你增加什么负担，会不会看完觉得：“哇我是不是遇到了什么奇怪的人？”",
      "也不知道这次相遇最后会在你那里留下些什么。",
      "但至少对我来说，带来了一些很好的变化。",
      "写下这些的目的也很简单一一一",
    ],
    hope: "希望这次偶然的相遇，最后真的能让我们都变得比原来更好一点。",
    apologyLead: [
      "至于这样自顾自地写了这么多，以及那天之后总是打扰你......",
      "嗯，还是先认真说一句：",
    ],
    finalLine: "抱歉，失礼了。",
    action: "后来呢",
  },
  calm: {
    chapter: "静心",
    time: "第二个星期",
    title: "世界之窗",
    paragraphs: [
      "时隔两周，我又来世界之窗啦！",
      "只是这次没有余音小朋友陪了（好多东西一个人玩会好尴尬！）",
      "今晚金莎会来唱歌，回头录上一段给你听。",
      "另一个来的目的，则是补上一些当时没拍的照片给你。",
    ],
    groups: [
      {
        id: "return",
        number: "01",
        title: "再次来到这里",
        note: "【这里填写刚到时的小对白】",
        phase: "morning",
      },
      {
        id: "makeup",
        number: "02",
        title: "补上上次没拍的东西",
        note: "【这里填写这一组的小对白】",
        phase: "day",
      },
      {
        id: "solo",
        number: "03",
        title: "一个人玩好尴尬",
        note: "【这里填写轻松一点的小吐槽】",
        phase: "day",
      },
      {
        id: "discover",
        number: "04",
        title: "今天看到的新东西",
        note: "【这里填写今天新发现的事物】",
        phase: "afternoon",
      },
      {
        id: "waiting",
        number: "05",
        title: "等待晚上的演出",
        note: "【这里填写等待演出时的小对白】",
        phase: "golden",
      },
    ] as const,
    photos: [
      {
        id: "03-01",
        src: "",
        alt: "再次来到世界之窗的主照片",
        group: "return",
        priority: "hero",
        date: "08.08",
        location: "世界之窗",
        caption: "【这里填写这一组的主要对白】",
        tag: "FOR YOU",
      },
      {
        id: "03-02",
        src: "",
        alt: "刚到时看到的场景",
        group: "return",
        priority: "normal",
        date: "08.08",
        location: "世界之窗",
        caption: "",
      },
      {
        id: "03-03",
        src: "",
        alt: "世界之窗当天的天气",
        group: "return",
        priority: "normal",
        date: "08.08",
        location: "世界之窗",
        caption: "",
      },
      {
        id: "03-04",
        src: "",
        alt: "刚到时的旅行碎片",
        group: "return",
        priority: "fragment",
        date: "08.08",
        location: "世界之窗",
        caption: "",
      },
      {
        id: "03-05",
        src: "",
        alt: "补拍照片一",
        group: "makeup",
        priority: "hero",
        date: "08.08",
        location: "世界之窗",
        caption: "【这里填写这一组的主要对白】",
        tag: "FOR YOU",
      },
      {
        id: "03-06",
        src: "",
        alt: "补拍照片二",
        group: "makeup",
        priority: "normal",
        date: "08.08",
        location: "世界之窗",
        caption: "",
      },
      {
        id: "03-07",
        src: "",
        alt: "补拍照片三",
        group: "makeup",
        priority: "normal",
        date: "08.08",
        location: "世界之窗",
        caption: "",
      },
      {
        id: "03-08",
        src: "",
        alt: "补拍照片四",
        group: "makeup",
        priority: "normal",
        date: "08.08",
        location: "世界之窗",
        caption: "",
      },
      {
        id: "03-09",
        src: "",
        alt: "补拍的旅行碎片",
        group: "makeup",
        priority: "fragment",
        date: "08.08",
        location: "世界之窗",
        caption: "",
      },
      {
        id: "03-10",
        src: "",
        alt: "一个人游玩的记录一",
        group: "solo",
        priority: "normal",
        date: "08.08",
        location: "世界之窗",
        caption: "",
      },
      {
        id: "03-11",
        src: "",
        alt: "一个人游玩的记录二",
        group: "solo",
        priority: "normal",
        date: "08.08",
        location: "世界之窗",
        caption: "",
      },
      {
        id: "03-12",
        src: "",
        alt: "一个人游玩的旅行碎片一",
        group: "solo",
        priority: "fragment",
        date: "08.08",
        location: "世界之窗",
        caption: "",
      },
      {
        id: "03-13",
        src: "",
        alt: "一个人游玩的旅行碎片二",
        group: "solo",
        priority: "fragment",
        date: "08.08",
        location: "世界之窗",
        caption: "",
      },
      {
        id: "03-14",
        src: "",
        alt: "今天发现的新东西主照片",
        group: "discover",
        priority: "hero",
        date: "08.08",
        location: "世界之窗",
        caption: "【这里填写这一组的主要对白】",
        tag: "KEEP",
      },
      {
        id: "03-15",
        src: "",
        alt: "今天发现的新东西记录一",
        group: "discover",
        priority: "normal",
        date: "08.08",
        location: "世界之窗",
        caption: "",
      },
      {
        id: "03-16",
        src: "",
        alt: "今天发现的新东西记录二",
        group: "discover",
        priority: "normal",
        date: "08.08",
        location: "世界之窗",
        caption: "",
      },
      {
        id: "03-17",
        src: "",
        alt: "今天发现的新东西旅行碎片",
        group: "discover",
        priority: "fragment",
        date: "08.08",
        location: "世界之窗",
        caption: "",
      },
      {
        id: "03-18",
        src: "",
        alt: "等待晚上演出的主照片",
        group: "waiting",
        priority: "hero",
        date: "08.08",
        location: "世界之窗",
        caption: "【这里填写等待演出时的主要对白】",
        tag: "KEEP",
      },
      {
        id: "03-19",
        src: "",
        alt: "等待晚上演出的记录照片",
        group: "waiting",
        priority: "normal",
        date: "08.08",
        location: "世界之窗",
        caption: "",
      },
      {
        id: "03-20",
        src: "",
        alt: "黄昏前的旅行碎片",
        group: "waiting",
        priority: "fragment",
        date: "08.08",
        location: "世界之窗",
        caption: "",
      },
    ] satisfies PhotoMemory[],
    afternoon: {
      label: "写于 8.8 下午",
      location: "在一个很像学校文艺晚会舞台的、空荡荡的室内座位上。",
    },
    reflection: ["【这里填写一至三句很轻的感受】"],
    night: {
      label: "黄昏之后",
      title: "今晚的声音",
      note: "回头录上一段给你听。",
      media: "现场视频 / 音频待补充",
    },
    nextChapter: "后来，我开始想一些更远的事情。",
    action: "04｜抉择",
  },
  blessing: {
    chapter: "祝愿",
    time: "第三个星期",
    title: "从过去，慢慢看向未来",
    items: [
      {
        label: "谢谢",
        caption: "【这里填写值得感谢的经历】",
      },
      {
        label: "成长",
        caption: "【这里填写这段经历带来的改变】",
      },
      {
        label: "祝愿",
        caption: "【这里填写想送给对方的祝愿】",
      },
    ],
    action: "去做最后的抉择",
  },
  choice: {
    time: "未来",
    title: "如果故事还有下一页，",
    subtitle: "你希望它是什么样子？",
    options: {
      a: {
        label: "停在这里",
        lines: ["最初的样子就很好。", "我们都有属于自己的世界。"],
      },
      b: {
        label: "以后，再见一次吧",
        lines: ["成为遥远、陌生，", "却依然很特别的现实朋友。"],
      },
    },
  },
  endings: {
    a: {
      chapter: "星河两岸",
      time: "未来",
      title: "谢谢你来过。",
      paragraphs: [
        "【这里填写 A 线正文】",
        "愿我们在各自的世界里，",
        "都成为比那时候更好的人。",
      ],
      closing: "完整结束，也是一种温柔。",
    },
    b: {
      chapter: "再次相逢",
      time: "未来",
      title: "那么，下次见。",
      paragraphs: [
        "也许我们不会再像从前一样，熟悉彼此的每一天。",
        "但偶尔知道，你正在世界的某个地方认真生活，似乎也很好。",
        "【这里填写 B 线正文】",
      ],
      closing: "把省略号，留给遥远的以后。",
    },
  },
  timeline: ["今夜", "分别后的第一周", "第二个星期", "第三个星期", "未来"],
} as const;
